// <auto-generated />
namespace MSContests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newClasses3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newClasses3));
        
        string IMigrationMetadata.Id
        {
            get { return "201407180218147_newClasses3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
